services:
  db:
    image: postgres:15.5-alpine
    container_name: user-service-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: user_service
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - user-net

  flyway:
    image: flyway/flyway:11.7-alpine
    container_name: user-service-flyway
    depends_on:
      - db
    volumes:
      - ./migrations/sql:/flyway/sql
    command: >
      -url=jdbc:postgresql://db:5432/user_service
      -user=user_service
      -locations=filesystem:/flyway/sql
      migrate
    networks:
      - user-net

volumes:
  user_data:

networks:
  user-net:
